<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DiamondDetect.Core\DiamondDetect.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
